name: Lint Code Base
on: [push, pull_request]

jobs:
  linter:
    name: Lint Code Base
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            **/node_modules/.cache
          key: ${{ runner.OS }}-lint-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-lint-
            ${{ runner.OS }}-
      - name: Install Dependencies
        run: npm install
      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          TYPESCRIPT_ES_CONFIG_FILE: .eslintrc.json
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_TYPESCRIPT_ES: true
          FILTER_REGEX_INCLUDE: .*(src|test)/.*
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          LOG_LEVEL: NOTICE
          DEFAULT_BRANCH: main
