name: Unit Test
on: [push, pull_request]

jobs:
  unittest:
    name: Unit Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            **/node_modules/.cache
          key: ${{ runner.OS }}-test-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-test-
      - name: Install Dependencies
        run: npm ci
      - name: Run Test
        run: npm run test
      - name: Run Coveralls
        run: npm run coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: 'coverage/lcov.info'
